### ISSUE TITLE
README

### ISSUE THREAD

**Issue by marcosfa00** [marcosfa00/MVC_Clinica_Dental#6]
A ver si puedes solucionar el tema de los Rearmes.md porque están mal y tu controlas más de esto @acastineiraduran ,
Basicamente los readme que estas bien, son los que están dentro de la carpeta del repositorio, pero el que esta fuera está mal, a ver si puedes organizarlo ^^

**Comment by angelcastineira** [comment]
Listo Pa

**Comment by marcosfa00** [comment]
perfect
